### ISSUE TITLE
DPS calculation is occasionally incorrect when using "Duplicate Tab" functionality in Chrome

### ISSUE THREAD

**Issue by AristocratMC** [umang-p/brainlets#24]
This is a very interesting bug. Haven't debugged to see what the actual cause is, but reproduction steps are as follows: 

- Open the sim. 
- Add G36Mod, and notice she does 16620 damage. 
- Right click the Chrome tab and Duplicate. 
- Add G36Mod in the new sim instance. 
- Observe that G36Mod does 3315 damage, which is clearly incorrect.

**Comment by umang-p** [comment]
Fixed in the commit mentioned above. 

The issue was related to when links are calculated when a doll is added to the echelon. When adding a mod3 doll, her level is set to 120 and then the element is disabled so it cannot be changed. When duplicating a tab with a mod3 doll, that doll slot would still have level 120 selected but disabled. When `changeDoll` was triggered by adding a new doll to the echelon, the new doll's links were being calculated before actually enabling/disabling the `option` elements as appropriate and selecting the correct default level value. This caused the doll added to that slot in the new instance to have only 1 link because in `getNumLinks` the `.doll-level-select` value could not be obtained because it seems jQuery does not let you read values of a disabled `option` element.

Fix was to just move the line where links are calculated to be after the section where the level select is changed, as it should have always been.

Thank you for reporting this.
